// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfdujfesqtfhdcbpvrms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmZHVqZmVzcXRmaGRjYnB2cm1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDQ4MTQsImV4cCI6MjA2NDAyMDgxNH0.T66ZdXKypw88fLqJ8REYtlu3wxxIJlQbzojnsazNhtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);